name = "web-analytics"
main = "src/index.ts"
compatibility_date = "2025-10-03"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/1 * * * *"]

[vars]
CF_ZONE_ID = "3324598d7b5168161d656336408e2be6"
CF_ACCOUNT_ID = "34a5e9d04deb1de3cbf7e71c75297db0"
CF_API_TOKEN = "N0ZR6XEChIgHQnZwBWwRTHBPRVeXQCYLoorBHJtC"


[[d1_databases]]
binding = "DB"
database_name = "rudl_app"
database_id = "6971cadc-b4f7-4642-bc78-f1e5e1bee999"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
logs = { enabled = true, include = "all" }