name = "rudlmonitor"
main = "src/index.ts"
compatibility_date = "2024-11-10"

[triggers]
crons = ["*/10 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "rudl-app"
database_id = "00000000-0000-0000-0000-000000000000"

[vars]
TELEGRAM_BOT_TOKEN = "placeholder"
